f=open('name.txt',mode='w')
f.write('Abhishek likes python\n')
f.write('And he is decent.')
f.close()
f=open('name.txt',mode='r')
print(f.name)
f.close()
f=open('name.txt',mode='r')
data=f.read()
print(data)
