f=open('name.txt',mode='w')
f.write('Abhishek likes python\n')
f.write('And he is decent.\n')
f.close()
f=open('name.txt',mode='r')
print(f.name)
f.close()
f=open('name.txt',mode='r')
data=f.read()
print(data)
f.close()
f=open('name.txt',mode='a')
f.write('mirzapur\n')
f.close()
