f=open('readline.txt',mode='w')
f.write('hello\n')
f.write("kabir singh\n")
f.write('Abhishek singh\n')
f=open('readline.txt',mode='a')
f.write('Himanshu sharma')
f.close()
f=open('readline.txt',mode='r')
ls=f.readlines()
print(len(ls))
f.close()